/**
 * Static reference data used by the analyzer and generator.
 * Kept free of runtime dependencies so it can be tree-shaken and reused
 * on both the server and the client.
 */

export const CHARSETS = {
  lowercase: 'abcdefghijklmnopqrstuvwxyz',
  uppercase: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ',
  numbers: '0123456789',
  symbols: '!@#$%^&*()-_=+[]{};:,.<>?/~',
} as const

/** Glyphs that are easily confused in most typefaces. */
export const AMBIGUOUS_CHARACTERS = 'Il1O0o|`\'";:.,'

/** Approximate size of the pool an attacker must brute-force per class. */
export const POOL_SIZES = {
  lowercase: 26,
  uppercase: 26,
  numbers: 10,
  symbols: 32,
  extended: 100,
} as const

/**
 * Attacker capability models. Numbers reflect publicly reported 2024-era
 * benchmarks for consumer/enterprise cracking rigs.
 */
export const ATTACK_MODELS = [
  {
    id: 'online-throttled',
    label: 'Online (throttled)',
    description: 'Rate-limited login form, 100 attempts/hour',
    hashesPerSecond: 100 / 3600,
  },
  {
    id: 'online-unthrottled',
    label: 'Online (unthrottled)',
    description: 'Credential stuffing against an unprotected endpoint',
    hashesPerSecond: 1_000,
  },
  {
    id: 'offline-bcrypt',
    label: 'Offline · bcrypt',
    description: 'Leaked bcrypt hashes, cost factor 10',
    hashesPerSecond: 20_000,
  },
  {
    id: 'offline-gpu',
    label: 'Offline · GPU rig',
    description: '8× RTX 4090 cluster against SHA-256',
    hashesPerSecond: 80_000_000_000,
  },
  {
    id: 'nation-state',
    label: 'Nation-state ASIC',
    description: 'Purpose-built hardware farm, MD5-class hashing',
    hashesPerSecond: 100_000_000_000_000,
  },
] as const

/** Rows used for keyboard-walk detection (QWERTY + numeric row). */
export const KEYBOARD_ROWS = [
  '`1234567890-=',
  'qwertyuiop[]\\',
  'asdfghjkl;\'',
  'zxcvbnm,./',
] as const

/** Top leaked passwords — trimmed to the highest-signal entries. */
export const COMMON_PASSWORDS = [
  '123456',
  'password',
  '123456789',
  '12345678',
  '12345',
  '1234567',
  'qwerty',
  'abc123',
  'password1',
  'iloveyou',
  '111111',
  '123123',
  'admin',
  'letmein',
  'welcome',
  'monkey',
  'dragon',
  'sunshine',
  'princess',
  'football',
  'baseball',
  'shadow',
  'master',
  'trustno1',
  'superman',
  'batman',
  'starwars',
  'whatever',
  'qazwsx',
  'passw0rd',
  'p@ssword',
  'zaq12wsx',
  'login',
  'guest',
  'root',
  'test',
  'hello',
  'freedom',
  'ninja',
  'azerty',
  'solo',
  'cheese',
  'summer',
  'internet',
  'samsung',
  'google',
  'chelsea',
  'liverpool',
  'arsenal',
  'pokemon',
  'minecraft',
  'computer',
  'michael',
  'jennifer',
  'jordan',
  'harley',
  'ranger',
  'hunter',
  'buster',
  'soccer',
  'hockey',
  'killer',
  'george',
  'andrew',
  'charlie',
  'thomas',
  'robert',
  'daniel',
] as const

/** Frequent English words that weaken a password even when embedded. */
export const DICTIONARY_WORDS = [
  'love',
  'god',
  'sex',
  'money',
  'secret',
  'cyber',
  'secure',
  'security',
  'hack',
  'hacker',
  'system',
  'server',
  'network',
  'access',
  'user',
  'name',
  'phone',
  'email',
  'house',
  'home',
  'work',
  'school',
  'college',
  'student',
  'teacher',
  'family',
  'friend',
  'happy',
  'angel',
  'devil',
  'tiger',
  'eagle',
  'lion',
  'wolf',
  'bear',
  'snake',
  'flower',
  'orange',
  'purple',
  'yellow',
  'green',
  'black',
  'white',
  'silver',
  'golden',
  'winter',
  'spring',
  'autumn',
  'january',
  'february',
  'march',
  'april',
  'june',
  'july',
  'august',
  'september',
  'october',
  'november',
  'december',
  'monday',
  'friday',
  'india',
  'china',
  'london',
  'paris',
  'tokyo',
  'york',
  'delhi',
  'mumbai',
] as const

/** EFF-style short wordlist for readable passphrases. */
export const PASSPHRASE_WORDS = [
  'anchor',
  'aurora',
  'basalt',
  'beacon',
  'binary',
  'bishop',
  'bramble',
  'bunker',
  'canyon',
  'cascade',
  'cipher',
  'cobalt',
  'comet',
  'copper',
  'crater',
  'cypher',
  'dagger',
  'delta',
  'dynamo',
  'ember',
  'entropy',
  'falcon',
  'fathom',
  'ferrite',
  'firewall',
  'flint',
  'fossil',
  'galaxy',
  'gambit',
  'granite',
  'harbor',
  'helium',
  'horizon',
  'ignite',
  'indigo',
  'ionize',
  'jigsaw',
  'kernel',
  'krypton',
  'lantern',
  'lattice',
  'ledger',
  'lumen',
  'magnet',
  'marble',
  'meteor',
  'mosaic',
  'nebula',
  'neutron',
  'nickel',
  'nomad',
  'obsidian',
  'octane',
  'onyx',
  'orbit',
  'outpost',
  'oxide',
  'packet',
  'phantom',
  'photon',
  'pigment',
  'pivot',
  'plasma',
  'prism',
  'quantum',
  'quarry',
  'quasar',
  'radar',
  'ranger',
  'ripple',
  'rivet',
  'rocket',
  'saffron',
  'sentry',
  'signal',
  'silica',
  'siphon',
  'solstice',
  'sonar',
  'spectrum',
  'sphinx',
  'stellar',
  'summit',
  'syntax',
  'tangent',
  'tempest',
  'thermal',
  'thorium',
  'tundra',
  'turbine',
  'umbra',
  'uranium',
  'vector',
  'velvet',
  'vertex',
  'vortex',
  'walnut',
  'warden',
  'willow',
  'xenon',
  'yonder',
  'zenith',
  'zephyr',
  'zodiac',
] as const

/** Consonant/vowel pools used to build pronounceable passwords. */
export const MEMORABLE_SYLLABLES = {
  consonants: ['b', 'c', 'd', 'f', 'g', 'k', 'l', 'm', 'n', 'p', 'r', 's', 't', 'v', 'z'],
  vowels: ['a', 'e', 'i', 'o', 'u'],
} as const

export const LEET_MAP: Record<string, string> = {
  '0': 'o',
  '1': 'i',
  '3': 'e',
  '4': 'a',
  '5': 's',
  '7': 't',
  '8': 'b',
  '@': 'a',
  $: 's',
  '!': 'i',
  '+': 't',
}

export const STRENGTH_META = {
  empty: { label: 'No input', token: 'muted-foreground', ratio: 0 },
  weak: { label: 'Weak', token: 'destructive', ratio: 0.2 },
  fair: { label: 'Fair', token: 'destructive', ratio: 0.38 },
  medium: { label: 'Medium', token: 'warning', ratio: 0.56 },
  strong: { label: 'Strong', token: 'primary', ratio: 0.78 },
  'very-strong': { label: 'Very Strong', token: 'success', ratio: 1 },
} as const

export const KEYBOARD_SHORTCUTS = [
  { keys: ['G'], description: 'Generate a new secure password' },
  { keys: ['C'], description: 'Copy the current password' },
  { keys: ['X'], description: 'Clear the analyzer' },
  { keys: ['V'], description: 'Toggle password visibility' },
  { keys: ['?'], description: 'Open the shortcut reference' },
] as const
